### ISSUE TITLE
Care to open a Discussion Tab?

### ISSUE THREAD

**Issue by sanjib-sen** [nur-zaman/valorantGPT#1]
Hi, I am a big fan of this project, and how much potential it has. The Valorant community is thankful for this super cool tool that can help to keep the focus on the actual game by auto-responding to chats so that we don't seem mean. 
I am hopeful that there is a Discussion tab to have some chitchats with the devs and have a hangout, a part of the reason this has to be submitted as an issue.

**Comment by nur-zaman** [comment]
Hi,
Thank you for your kind words and suggestion! Created a Discussion tab. Feel free to share any further thoughts or ideas.
