### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Luongzz** [nur-zaman/valorantGPT#2]
`Traceback (most recent call last):
  File "C:\Users\Yoshino\Desktop\Bot\tools\valorantGPT-master\run.py", line 14, in <module>
    config = json.load(open(r"config.json"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 285: character maps to <undefined>`

**Comment by nur-zaman** [comment]
Should be working now , check [this](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character#9233174) for details

**Comment by Luongzz** [comment]
thank u
